In [1]:
!pip install autogluon

Collecting autogluon
  Downloading autogluon-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon
  Downloading autogluon-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.core==1.5.0 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.core==1.5.0 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.features==1.5.0 (from autogluon)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.features==1.5.0 (from autogluon)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.tabular==1.5.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Collecting autogluon.tabular==1.5.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Collecting autogluon.multimodal==1.5.0 (from autogluon)
  Downloading autogluon_multimodal-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.multimodal==1.5.0 (from autogluon)
  Downloading autogluon_multimodal-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.timeseries==1.5.0 (from autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading autogluon_timeseries-1.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.16.3)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.6.1)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.2.2)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.32.4)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.10.0)
Collecting autogluon.timeseries==1.5.0 (from autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading autogluon_timeseries-1.5.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.16.3)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.6.1)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.2.2)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (2.32.4)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading boto3-1.42.70-py3-none-any.whl.metadata (6.7 kB)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading boto3-1.42.70-py3-none-any.whl.metadata (6.7 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.core[all]==1.5.0->autogluon)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Collecting ray<2.53,>=2.43.0 (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0->autogluon)
  Downloading ray-2.52.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (18.1.0)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (0.2.7)
Collecting stevedore<5.5 (from autogluon.core[all]==1.5.0->autogluon)
Collecting ray<2.53,>=2.43.0 (from ray[default,tune]<2.53,>=2.43.0; (platform_system != "Windows" or python_version != "3.13") and extra == "all"->autogluon.core[all]==1.5.0->autogluon)
  Downloading ray-2.52.1-cp312-cp312-manylinux2014_x86_64.whl.metadata (21 kB)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (18.1.0)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.core[all]==1.5.0->autogluon) (0.2.7)
Collecting stevedore<5.5 (from autogluon.core[all]==1.5.0->autogluon)
  Downloading stevedore-5.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: Pillow<12,>=10.0.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (11.3.0)
  Downloading stevedore-5.4.1-py3-none-any.whl.metadata (2.3 kB)
Requirement already satisfied: Pillow<12,>=10.0.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (11.3.0)
Collecting torch<2.10,>=2.6 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting torch<2.10,>=2.6 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torch-2.9.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (30 kB)
Collecting lightning<2.6,>=2.5.1 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning-2.5.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 3.5 MB/s eta 0:00:00
Collecting lightning<2.6,>=2.5.1 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading lightning-2.5.6-py3-none-any.whl.metadata (42 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.4/42.4 kB 3.5 MB/s eta 0:00:00
Collecting transformers<4.58,>=4.51.0 (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.4 MB/s eta 0:00:00
Collecting transformers<4.58,>=4.51.0 (from transformers[sentencepiece]<4.58,>=4.51.0->autogluon.multimodal==1.5.0->autogluon)
  Downloading transformers-4.57.6-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.0/44.0 kB 3.4 MB/s eta 0:00:00
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.13.0)
Requirement already satisfied: fsspec<=2025.3 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (2025.3.0)
Collecting jsonschema<4.24,>=4.18 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.4 MB/s eta 0:00:00
Requirement already satisfied: accelerate<2.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.13.0)
Requirement already satisfied: fsspec<=2025.3 in /usr/local/lib/python3.12/dist-packages (from fsspec[http]<=2025.3->autogluon.multimodal==1.5.0->autogluon) (2025.3.0)
Collecting jsonschema<4.24,>=4.18 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading jsonschema-4.23.0-py3-none-any.whl.metadata (7.9 kB)
Collecting seqeval<1.3.0,>=1.2.2 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading seqeval-1.2.2.tar.gz (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting evaluate<0.5.0,>=0.4.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
  Preparing metadata (setup.py) ... done
Collecting evaluate<0.5.0,>=0.4.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading evaluate-0.4.6-py3-none-any.whl.metadata (9.5 kB)
Collecting timm<1.0.7,>=0.9.5 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading timm-1.0.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.1 MB/s eta 0:00:00
Collecting timm<1.0.7,>=0.9.5 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading timm-1.0.3-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.1 MB/s eta 0:00:00
Collecting torchvision<0.25.0,>=0.21.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.25.2)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.3)
Collecting torchmetrics<1.8,>=1.2.0 (from autogluon.multimodal==1.5.0->autogluon)
Collecting torchvision<0.25.0,>=0.21.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchvision-0.24.1-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (5.9 kB)
Requirement already satisfied: scikit-image<0.26.0,>=0.19.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.25.2)
Requirement already satisfied: text-unidecode<1.4,>=1.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (1.3)
Collecting torchmetrics<1.8,>=1.2.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading torchmetrics-1.7.4-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: omegaconf<2.4.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.3.0)
Collecting pytorch-metric-learning<2.9,>=1.3.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_metric_learning-2.8.1-py3-none-any.whl.metadata (18 kB)
  Downloading torchmetrics-1.7.4-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: omegaconf<2.4.0,>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.3.0)
Collecting pytorch-metric-learning<2.9,>=1.3.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytorch_metric_learning-2.8.1-py3-none-any.whl.metadata (18 kB)
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: nltk<3.10,>=3.4.5 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.9.1)
Collecting nlpaug<1.2.0,>=1.1.10 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nlpaug-1.1.11-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: nltk<3.10,>=3.4.5 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.9.1)
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.1.6)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.19.0)
Collecting pytesseract<0.4,>=0.3.9 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-ml-py3<8.0,>=7.352.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)
Collecting openmim<0.4.0,>=0.3.7 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading openmim-0.3.9-py2.py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: defusedxml<0.7.2,>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (0.7.1)
Requirement already satisfied: jinja2<3.2,>=3.0.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (3.1.6)
Requirement already satisfied: tensorboard<3,>=2.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.multimodal==1.5.0->autogluon) (2.19.0)
Collecting pytesseract<0.4,>=0.3.9 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pytesseract-0.3.13-py3-none-any.whl.metadata (11 kB)
Collecting nvidia-ml-py3<8.0,>=7.352.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading nvidia-ml-py3-7.352.0.tar.gz (19 kB)
  Preparing metadata (setup.py) ... done
Collecting pdf2image<1.19,>=1.17.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting einx (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading einx-0.4.2-py3-none-any.whl.metadata (6.9 kB)
  Preparing metadata (setup.py) ... done
Collecting pdf2image<1.19,>=1.17.0 (from autogluon.multimodal==1.5.0->autogluon)
  Downloading pdf2image-1.17.0-py3-none-any.whl.metadata (6.2 kB)
Collecting einx (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading einx-0.4.2-py3-none-any.whl.metadata (6.9 kB)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (4.6.0)
Collecting huggingface_hub<1.0 (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: lightgbm<4.7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (4.6.0)
Collecting huggingface_hub<1.0 (from huggingface_hub[torch]<1.0; extra == "all"->autogluon.tabular[all]==1.5.0->autogluon)
  Downloading huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting xgboost<3.2,>=2.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading xgboost-3.1.3-py3-none-manylinux_2_28_x86_64.whl.metadata (2.0 kB)
Collecting xgboost<3.2,>=2.0 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading xgboost-3.1.3-py3-none-manylinux_2_28_x86_64.whl.metadata (2.0 kB)
Collecting catboost<1.3,>=1.2 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (2.8.7)
Collecting loguru (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops<0.9,>=0.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (0.8.2)
Requirement already satisfied: spacy<3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (3.8.11)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (1.5.3)
Collecting catboost<1.3,>=1.2 (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading catboost-1.2.10-cp312-cp312-manylinux2014_x86_64.whl.metadata (1.2 kB)
Requirement already satisfied: fastai<2.9,>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (2.8.7)
Collecting loguru (from autogluon.tabular[all]==1.5.0->autogluon)
  Downloading loguru-0.7.3-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: einops<0.9,>=0.7 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (0.8.2)
Requirement already satisfied: spacy<3.9 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular[all]==1.5.0->autogluon) (3.8.11)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon) (1.5.3)
Collecting gluonts<0.17,>=0.15.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading gluonts-0.16.2-py3-none-any.whl.metadata (9.8 kB)
Collecting gluonts<0.17,>=0.15.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading gluonts-0.16.2-py3-none-any.whl.metadata (9.8 kB)
Collecting statsforecast<2.0.2,>=1.7.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading statsforecast-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (29 kB)
Collecting mlforecast<0.15.0,>=0.14.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading mlforecast-0.14.0-py3-none-any.whl.metadata (12 kB)
Collecting utilsforecast<0.2.12,>=0.2.3 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
Collecting statsforecast<2.0.2,>=1.7.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading statsforecast-2.0.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (29 kB)
Collecting mlforecast<0.15.0,>=0.14.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading mlforecast-0.14.0-py3-none-any.whl.metadata (12 kB)
Collecting utilsforecast<0.2.12,>=0.2.3 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading utilsforecast-0.2.11-py3-none-any.whl.metadata (7.7 kB)
Collecting coreforecast<0.0.17,>=0.0.12 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading coreforecast-0.0.16-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)
Collecting fugue>=0.9.0 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading fugue-0.9.7-py3-none-any.whl.metadata (18 kB)
  Downloading utilsforecast-0.2.11-py3-none-any.whl.metadata (7.7 kB)
Collecting coreforecast<0.0.17,>=0.0.12 (from autogluon.timeseries==1.5.0->autogluon.timeseries[all]==1.5.0->autogluon)
  Downloading coreforecast-0.0.16-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.7 kB)

In [2]:
import os
import joblib
import warnings
os.environ["OMP_NUM_THREADS"] = "1"
import numpy as np
import pandas as pd
from google.colab import files
from sklearn.svm import SVR
from google.colab import files
import matplotlib.pyplot as plt
from statsmodels.tsa.arima.model import ARIMA
from autogluon.tabular import TabularPredictor
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [3]:
# Open a file upload dialog
uploaded = files.upload()

Saving Cleaned Dataset.csv to Cleaned Dataset.csv

In [4]:
# Import dataset
dataset = pd.read_csv("Cleaned Dataset.csv")
dataset

,Country,Year,BEV Percentage (Total Number Of Registrations),GDP,CPI,EG,Recharging Points,AC Recharging Speed (km/h),DC Recharging Speed (km/h),Available,Battery Capacity,Real Range,Purchase price (EUR),Log_BEV Percentage (Total Number Of Registrations),Log_Recharging Points,Log_GDP,Log_CPI,Log_EG,Log_Available,Log_AC Recharging Speed (km/h)
0,Austria,2020,6.41,3.803179e+05,1.381911,-1.600,26797.00000,39.325301,403.164557,97.000000,57.761446,286.200000,38311.380000,2.002830,10.196083,12.848765,0.867903,NaN,4.584967,3.696979
1,Austria,2021,13.92,4.062315e+05,2.766667,2.000,39904.00000,40.904348,493.391304,168.000000,64.046957,308.730000,40745.010000,2.702703,10.594257,12.914681,1.326190,1.098612,5.129899,3.735390
2,Austria,2022,15.70,4.493822e+05,8.546870,2.700,61393.00000,49.314815,594.259259,253.000000,73.787037,345.440000,43874.270000,2.815409,11.025067,13.015631,2.256213,1.308333,5.537334,3.918300
3,Austria,2023,19.91,4.778373e+05,7.814134,0.800,76773.00000,70.307692,649.230769,371.000000,79.230769,379.510785,45999.050000,3.040228,11.248621,13.077028,2.176357,0.587787,5.918894,4.267004
4,Austria,2024,17.58,4.940876e+05,2.937916,0.100,102562.00000,92.176355,744.736940,551.323143,88.123464,416.941976,48874.922228,2.922086,11.538233,13.110470,1.370652,0.095310,6.314133,4.534494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,Sweden,2021,19.09,5.417760e+06,2.163197,1.300,70537.00000,40.904348,493.391304,168.000000,64.046957,308.730000,40745.010000,3.000222,11.163907,15.505193,1.151583,0.832909,5.129899,3.735390
158,Sweden,2022,32.84,5.816415e+06,8.369291,3.500,83510.00000,49.314815,594.259259,253.000000,73.787037,345.440000,43874.270000,3.521644,11.332734,15.576195,2.237437,1.504077,5.537334,3.918300
159,Sweden,2023,38.42,6.143187e+06,8.548625,1.200,126758.00000,70.307692,649.230769,371.000000,79.230769,379.510785,45999.050000,3.674273,11.750043,15.630854,2.256397,0.788457,5.918894,4.267004
160,Sweden,2024,34.99,6.379843e+06,2.835817,-0.300,189977.00000,92.176355,744.736940,551.323143,88.123464,416.941976,48874.922228,3.583241,12.154664,15.668654,1.344382,-0.356675,6.314133,4.534494
161,Sweden,2025,36.58,6.625616e+06,0.679869,0.075,284725.70196,120.847095,854.292704,819.291667,98.014256,458.065010,51930.594713,3.626472,12.559285,15.706454,0.518716,0.072321,6.709660,4.802767

,Country,Year,BEV Percentage (Total Number Of Registrations),GDP,CPI,EG,Recharging Points,AC Recharging Speed (km/h),DC Recharging Speed (km/h),Available,Battery Capacity,Real Range,Purchase price (EUR),Log_BEV Percentage (Total Number Of Registrations),Log_Recharging Points,Log_GDP,Log_CPI,Log_EG,Log_Available,Log_AC Recharging Speed (km/h)
0,Austria,2020,6.41,3.803179e+05,1.381911,-1.600,26797.00000,39.325301,403.164557,97.000000,57.761446,286.200000,38311.380000,2.002830,10.196083,12.848765,0.867903,NaN,4.584967,3.696979
1,Austria,2021,13.92,4.062315e+05,2.766667,2.000,39904.00000,40.904348,493.391304,168.000000,64.046957,308.730000,40745.010000,2.702703,10.594257,12.914681,1.326190,1.098612,5.129899,3.735390
2,Austria,2022,15.70,4.493822e+05,8.546870,2.700,61393.00000,49.314815,594.259259,253.000000,73.787037,345.440000,43874.270000,2.815409,11.025067,13.015631,2.256213,1.308333,5.537334,3.918300
3,Austria,2023,19.91,4.778373e+05,7.814134,0.800,76773.00000,70.307692,649.230769,371.000000,79.230769,379.510785,45999.050000,3.040228,11.248621,13.077028,2.176357,0.587787,5.918894,4.267004
4,Austria,2024,17.58,4.940876e+05,2.937916,0.100,102562.00000,92.176355,744.736940,551.323143,88.123464,416.941976,48874.922228,2.922086,11.538233,13.110470,1.370652,0.095310,6.314133,4.534494
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,Sweden,2021,19.09,5.417760e+06,2.163197,1.300,70537.00000,40.904348,493.391304,168.000000,64.046957,308.730000,40745.010000,3.000222,11.163907,15.505193,1.151583,0.832909,5.129899,3.735390
158,Sweden,2022,32.84,5.816415e+06,8.369291,3.500,83510.00000,49.314815,594.259259,253.000000,73.787037,345.440000,43874.270000,3.521644,11.332734,15.576195,2.237437,1.504077,5.537334,3.918300
159,Sweden,2023,38.42,6.143187e+06,8.548625,1.200,126758.00000,70.307692,649.230769,371.000000,79.230769,379.510785,45999.050000,3.674273,11.750043,15.630854,2.256397,0.788457,5.918894,4.267004
160,Sweden,2024,34.99,6.379843e+06,2.835817,-0.300,189977.00000,92.176355,744.736940,551.323143,88.123464,416.941976,48874.922228,3.583241,12.154664,15.668654,1.344382,-0.356675,6.314133,4.534494
161,Sweden,2025,36.58,6.625616e+06,0.679869,0.075,284725.70196,120.847095,854.292704,819.291667,98.014256,458.065010,51930.594713,3.626472,12.559285,15.706454,0.518716,0.072321,6.709660,4.802767

In [5]:
# Define the target
target = 'Log_BEV Percentage (Total Number Of Registrations)'

In [8]:
# Load the PCA tools
tools = joblib.load("pca_processors.pkl")
scaler = tools['scaler']
pca = tools['pca_model']
features = tools['feature_names']

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator StandardScaler from version 1.3.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator PCA from version 1.3.0 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

In [9]:
# Split the dataset into train and test data
pre_covid_df = dataset[dataset['Year'].between(2020, 2024)].copy()
post_covid_df = dataset[dataset['Year'] >= 2025].copy()

Please refer the jupyter notebook - **3.1.Feature Selection_BEV Percentage (Primary Target)** to understand the imputation

In [10]:
# Check which columns have NaNs and how many
print("Missing Values Per Column on Train data (2020-2024)")
print(pre_covid_df[features].isna().sum())

print("\nMissing Values Per Column Test data (2025)")
print(post_covid_df[features].isna().sum())

Missing Values Per Column on Train data (2020-2024)
DC Recharging Speed (km/h)         0
Log_Recharging Points              1
Real Range                         0
Purchase price (EUR)               0
Log_Available                      0
Log_AC Recharging Speed (km/h)     0
Battery Capacity                   0
Log_GDP                            0
Log_CPI                            1
Log_EG                            22
dtype: int64

Missing Values Per Column Test data (2025)
DC Recharging Speed (km/h)        0
Log_Recharging Points             0
Real Range                        0
Purchase price (EUR)              0
Log_Available                     0
Log_AC Recharging Speed (km/h)    0
Battery Capacity                  0
Log_GDP                           0
Log_CPI                           0
Log_EG                            0
dtype: int64

In [11]:
# Checking which rows are empty
print("Missing Log_EG in Train data (2020-2024)")
print(pre_covid_df[pre_covid_df['Log_EG'].isna()].reset_index()[['Country', 'Year', 'Log_EG']])

Missing Log_EG in Train data (2020-2024)
           Country  Year  Log_EG
0          Austria  2020     NaN
1         Bulgaria  2020     NaN
2          Croatia  2020     NaN
3   Czech Republic  2020     NaN
4          Denmark  2020     NaN
5          Estonia  2020     NaN
6          Finland  2020     NaN
7          Finland  2024     NaN
8           Greece  2020     NaN
9          Hungary  2020     NaN
10         Hungary  2024     NaN
11         Ireland  2020     NaN
12           Italy  2020     NaN
13          Latvia  2021     NaN
14          Latvia  2024     NaN
15       Lithuania  2020     NaN
16        Portugal  2020     NaN
17         Romania  2020     NaN
18         Romania  2023     NaN
19        Slovakia  2020     NaN
20           Spain  2020     NaN
21          Sweden  2020     NaN

In [12]:
features_to_impute = ['Log_Recharging Points', 'Log_EG', 'Log_CPI']

# Compute per-country median from train
train_country_medians = {}
train_global_medians = {}

for col in features_to_impute:
    train_country_medians[col] = pre_covid_df.groupby('Country')[col].median()
    train_global_medians[col] = pre_covid_df[col].median()

def robust_impute(df, country_medians, global_medians):
    df_copy = df.copy()
    for col in features_to_impute:

        # Impute per-country median
        df_copy[col] = df_copy[col].fillna(df_copy['Country'].map(country_medians[col]))

        # Fallback to global median if still NaN
        df_copy[col] = df_copy[col].fillna(global_medians[col])
    return df_copy

# Apply to train and test
pre_covid_fixed = robust_impute(pre_covid_df, train_country_medians, train_global_medians)
post_covid_fixed = robust_impute(post_covid_df, train_country_medians, train_global_medians)

In [13]:
# Verfication
print("Missing Values Per Column on Train data (2020-2024)")
print(pre_covid_fixed[features].isna().sum())

print("\nMissing Values Per Column Test data (2025)")
print(post_covid_fixed[features].isna().sum())

Missing Values Per Column on Train data (2020-2024)
DC Recharging Speed (km/h)        0
Log_Recharging Points             0
Real Range                        0
Purchase price (EUR)              0
Log_Available                     0
Log_AC Recharging Speed (km/h)    0
Battery Capacity                  0
Log_GDP                           0
Log_CPI                           0
Log_EG                            0
dtype: int64

Missing Values Per Column Test data (2025)
DC Recharging Speed (km/h)        0
Log_Recharging Points             0
Real Range                        0
Purchase price (EUR)              0
Log_Available                     0
Log_AC Recharging Speed (km/h)    0
Battery Capacity                  0
Log_GDP                           0
Log_CPI                           0
Log_EG                            0
dtype: int64

In [14]:
X_train_scaled = scaler.transform(pre_covid_fixed[features])
X_test_scaled = scaler.transform(post_covid_fixed[features])

# Convert back to DataFrame to keep column names
X_train_scaled = pd.DataFrame(X_train_scaled, columns=features)
X_test_scaled = pd.DataFrame(X_test_scaled, columns=features)

In [15]:
# Transform the features into 2 Principal Components using the loaded PCA model
# and convert them back to a dataframe for easy handling
X_train_pca = pd.DataFrame(pca.transform(X_train_scaled), columns=['PC1', 'PC2', 'PC3'], index=pre_covid_fixed.index)
X_test_pca = pd.DataFrame(pca.transform(X_test_scaled), columns=['PC1', 'PC2', 'PC3'], index=post_covid_fixed.index)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but PCA was fitted without feature names
  warnings.warn(

In [16]:
# Define the targets
y_train = pre_covid_fixed[target]
y_test = post_covid_fixed[target]

print(f"Train Shape (PCs): {X_train_pca.shape}")
print(f"Test Shape (PCs): {X_test_pca.shape}")

Train Shape (PCs): (135, 3)
Test Shape (PCs): (27, 3)

In [17]:
# Define the clusters based on the K-Means clusters + PCA
leaders_list = [
    "Austria", "Belgium", "Czech Republic", "Denmark", "France",
    "Germany", "Hungary", "Italy", "Netherlands", "Poland",
    "Romania", "Spain", "Sweden"
]

followers_list = [
    "Bulgaria", "Croatia", "Cyprus", "Estonia", "Finland",
    "Greece", "Ireland", "Latvia", "Lithuania", "Luxembourg",
    "Malta", "Portugal", "Slovakia", "Slovenia"
]

In [18]:
# Filter Training Data
X_train_leaders = X_train_pca[pre_covid_fixed['Country'].isin(leaders_list)]
y_train_leaders = y_train[pre_covid_fixed['Country'].isin(leaders_list)]

X_train_followers = X_train_pca[pre_covid_fixed['Country'].isin(followers_list)]
y_train_followers = y_train[pre_covid_fixed['Country'].isin(followers_list)]

# Filter Testing Data
X_test_leaders = X_test_pca[post_covid_fixed['Country'].isin(leaders_list)]
y_test_leaders = y_test[post_covid_fixed['Country'].isin(leaders_list)]

X_test_followers = X_test_pca[post_covid_fixed['Country'].isin(followers_list)]
y_test_followers = y_test[post_covid_fixed['Country'].isin(followers_list)]

## AUTOGLUON MODEL

**1. Explanation:** [AutoGluon](https://aws.amazon.com/blogs/opensource/machine-learning-with-autogluon-an-open-source-automl-library/)

**2. Documentation:** [Link](https://auto.gluon.ai/stable/index.html)

**3. GitHub Repository:** [Link](https://github.com/autogluon/autogluon)

In [19]:
# Prepare data function for AutoGluon: AutoGluon needs all the PCs and the target in a single DataFrame as its designed to work on Pandas dataframe.
def prepare_ag_data(X_pca, y_target):
    df = pd.DataFrame(X_pca, columns=[f'PC{i+1}' for i in range(X_pca.shape[1])])
    df['target'] = y_target.values
    return df

train_data_ag = prepare_ag_data(X_train_pca, y_train)
test_data_ag = prepare_ag_data(X_test_pca, y_test)

In [20]:
# Train AutoGluon and fit the model
predictor = TabularPredictor(
    label='target', # 'Log_BEV Percentage (Total Number Of Registrations)'
    problem_type='regression', # Prediction of continuous numbers
    eval_metric='mean_absolute_error' # 'mean_absolute_error' because R2 is unstable for single-year tests
).fit(
    train_data_ag, # Training data
    presets='best_quality', # Enables stacking and ensembling for higher accuracy
    time_limit=600          # 10-minute training limit. Will try to train as many model combinations as possible within this window.
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260318_184643"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Mon Feb  2 12:27:57 UTC 2026
CPU Count:          2
Pytorch Version:    2.9.1+cu128
CUDA Version:       CUDA is not available
Memory Avail:       10.98 GB / 12.67 GB (86.7%)
Disk Space Avail:   74.86 GB / 107.72 GB (69.5%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 150s of the 600s of remaining time (25%).
	Running DyStack sub-fit in a ray process to avoid memory leakage. Enabling ray logging (enable_ray_logging=True). Specify `ds_args={'enable_ray_logging': False}` if you experience logging issues.
2026-03-18 18:47:10,486	INFO worker.py:2014 -- Started a local Ray instance. View the dashboard at http://127.0.0.1:8265
/usr/local/lib/python3.12/dist-packages/ray/_private/worker.py:2062: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
		Context path: "/content/AutogluonModels/ag-20260318_184643/ds_sub_fit/sub_fit_ho"
(_dystack pid=2986) Running DyStack sub-fit ...
(_dystack pid=2986) Beginning AutoGluon training ... Time limit = 129s
(_dystack pid=2986) AutoGluon will save models to "/content/AutogluonModels/ag-20260318_184643/ds_sub_fit/sub_fit_ho"
(_dystack pid=2986) Train Data Rows:    120
(_dystack pid=2986) Train Data Columns: 3
(_dystack pid=2986) Label Column:       target
(_dystack pid=2986) Problem Type:       regression
(_dystack pid=2986) Preprocessing data ...
(_dystack pid=2986) Using Feature Generators to preprocess the data ...
(_dystack pid=2986) Fitting AutoMLPipelineFeatureGenerator...
(_dystack pid=2986) 	Available Memory:                    10055.31 MB
(_dystack pid=2986) 	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
(_dystack pid=2986) 	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
(_dystack pid=2986) 	Stage 1 Generators:
(_dystack pid=2986) 		Fitting AsTypeFeatureGenerator...
(_dystack pid=2986) 	Stage 2 Generators:
(_dystack pid=2986) 		Fitting FillNaFeatureGenerator...
(_dystack pid=2986) 	Stage 3 Generators:
(_dystack pid=2986) 		Fitting IdentityFeatureGenerator...
(_dystack pid=2986) 	Stage 4 Generators:
(_dystack pid=2986) 		Fitting DropUniqueFeatureGenerator...
(_dystack pid=2986) 	Stage 5 Generators:
(_dystack pid=2986) 		Fitting DropDuplicatesFeatureGenerator...
(_dystack pid=2986) 	Types of features in original data (raw dtype, special dtypes):
(_dystack pid=2986) 		('float', []) : 3 | ['PC1', 'PC2', 'PC3']
(_dystack pid=2986) 	Types of features in processed data (raw dtype, special dtypes):
(_dystack pid=2986) 		('float', []) : 3 | ['PC1', 'PC2', 'PC3']
(_dystack pid=2986) 	0.0s = Fit runtime
(_dystack pid=2986) 	3 features in original data used to generate 3 features in processed data.
(_dystack pid=2986) 	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
(_dystack pid=2986) Data preprocessing and feature engineering runtime = 0.03s ...
(_dystack pid=2986) AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
(_dystack pid=2986) 	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
(_dystack pid=2986) 	To change this, specify the eval_metric parameter of Predictor()
(_dystack pid=2986) Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
(_dystack pid=2986) User-specified model hyperparameters to be fit:
(_dystack pid=2986) {
(_dystack pid=2986) 	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
(_dystack pid=2986) 	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
(_dystack pid=2986) 	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
(_dystack pid=2986) 	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
(_dystack pid=2986) 	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
(_dystack pid=2986) 	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=2986) 	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
(_dystack pid=2986) }
(_dystack pid=2986) AutoGluon will fit 2 stack levels (L1 to L2) ...
(_dystack pid=2986) Fitting 106 L1 models, fit_strategy="sequential" ...
(_dystack pid=2986) Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 86.28s of the 129.43s of remaining time.
(_dystack pid=2986) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.16%)

(_ray_fit pid=3444) [1000]	valid_set's l1: 0.530227
(_ray_fit pid=3444) [2000]	valid_set's l1: 0.516057
(_ray_fit pid=3444) [3000]	valid_set's l1: 0.510887
(_ray_fit pid=3444) [4000]	valid_set's l1: 0.509313
(_ray_fit pid=3547) [1000]	valid_set's l1: 0.39012

(_dystack pid=2986) 	-0.5372	 = Validation score   (-mean_absolute_error)
(_dystack pid=2986) 	32.57s	 = Training   runtime
(_dystack pid=2986) 	0.03s	 = Validation runtime
(_dystack pid=2986) Fitting model: LightGBM_BAG_L1 ... Training model for up to 45.48s of the 88.63s of remaining time.
(_dystack pid=2986) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.16%)
(_dystack pid=2986) 	-0.562	 = Validation score   (-mean_absolute_error)
(_dystack pid=2986) 	28.31s	 = Training   runtime
(_dystack pid=2986) 	0.01s	 = Validation runtime
(_dystack pid=2986) Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 12.22s of the 55.37s of remaining time.
(_dystack pid=2986) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2986) 	-0.6009	 = Validation score   (-mean_absolute_error)
(_dystack pid=2986) 	1.53s	 = Training   runtime
(_dystack pid=2986) 	0.14s	 = Validation runtime
(_dystack pid=2986) Fitting model: CatBoost_BAG_L1 ... Training model for up to 10.53s of the 53.68s of remaining time.
(_dystack pid=2986) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=3.89%)
(_dystack pid=2986) 	Time limit exceeded... Skipping CatBoost_BAG_L1.
(_dystack pid=2986) Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 1.27s of the 44.42s of remaining time.
(_dystack pid=2986) 	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
(_dystack pid=2986) 	-0.6074	 = Validation score   (-mean_absolute_error)
(_dystack pid=2986) 	1.59s	 = Training   runtime
(_dystack pid=2986) 	0.13s	 = Validation runtime
(_dystack pid=2986) Fitting model: WeightedEnsemble_L2 ... Training model for up to 129.46s of the 42.59s of remaining time.
(_dystack pid=2986) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.6 GB
(_dystack pid=2986) 	Ensemble Weights: {'LightGBMXT_BAG_L1': 1.0}
(_dystack pid=2986) 	-0.5372	 = Validation score   (-mean_absolute_error)
(_dystack pid=2986) 	0.04s	 = Training   runtime
(_dystack pid=2986) 	0.0s	 = Validation runtime
(_dystack pid=2986) Fitting 106 L2 models, fit_strategy="sequential" ...
(_dystack pid=2986) Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 42.55s of the 42.52s of remaining time.
(_dystack pid=2986) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.16%)

(_ray_fit pid=4481) [1000]	valid_set's l1: 0.466548
(_ray_fit pid=4481) [2000]	valid_set's l1: 0.441954

(_dystack pid=2986) 	-0.5182	 = Validation score   (-mean_absolute_error)
(_dystack pid=2986) 	29.37s	 = Training   runtime
(_dystack pid=2986) 	0.05s	 = Validation runtime
(_dystack pid=2986) Fitting model: LightGBM_BAG_L2 ... Training model for up to 8.82s of the 8.80s of remaining time.
(_dystack pid=2986) 	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.17%)
(_dystack pid=2986) 	-0.5434	 = Validation score   (-mean_absolute_error)
(_dystack pid=2986) 	29.02s	 = Training   runtime
(_dystack pid=2986) 	0.04s	 = Validation runtime
(_dystack pid=2986) Fitting model: WeightedEnsemble_L3 ... Training model for up to 129.46s of the -25.33s of remaining time.
(_dystack pid=2986) 	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.2 GB
(_dystack pid=2986) 	Ensemble Weights: {'LightGBMXT_BAG_L2': 1.0}
(_dystack pid=2986) 	-0.5182	 = Validation score   (-mean_absolute_error)
(_dystack pid=2986) 	0.05s	 = Training   runtime
(_dystack pid=2986) 	0.0s	 = Validation runtime
(_dystack pid=2986) AutoGluon training complete, total runtime = 154.89s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 136.3 rows/s (15 batch size)
(_dystack pid=2986) TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20260318_184643/ds_sub_fit/sub_fit_ho")
(_dystack pid=2986) Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                    model  score_holdout  score_val          eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0         LightGBM_BAG_L1      -0.689642  -0.562015  mean_absolute_error        0.017369       0.014132  28.306532                 0.017369                0.014132          28.306532            1       True          2
1       LightGBMXT_BAG_L1      -0.711646  -0.537190  mean_absolute_error        1.055200       0.025461  32.570963                 1.055200                0.025461          32.570963            1       True          1
2     WeightedEnsemble_L2      -0.711646  -0.537190  mean_absolute_error        1.057573       0.026412  32.609836                 0.002373                0.000950           0.038874            2       True          5
3         LightGBM_BAG_L2      -0.717968  -0.543426  mean_absolute_error        1.276397       0.328308  64.713101                 0.019008                0.036350          29.017745            2       True          7
4       LightGBMXT_BAG_L2      -0.729535  -0.518234  mean_absolute_error        1.304076       0.343051  65.060815                 0.046687                0.051094          29.365458            2       True          6
5     WeightedEnsemble_L3      -0.729535  -0.518234  mean_absolute_error        1.305905       0.344312  65.114456                 0.001829                0.001260           0.053641            3       True          8
6  RandomForestMSE_BAG_L1      -0.729838  -0.600863  mean_absolute_error        0.102176       0.141260   1.532449                 0.102176                0.141260           1.532449            1       True          3
7    ExtraTreesMSE_BAG_L1      -0.731271  -0.607394  mean_absolute_error        0.100013       0.125236   1.591945                 0.100013                0.125236           1.591945            1       True          4
	0	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: True)
	184s	 = DyStack   runtime |	416s	 = Remaining runtime
Starting main fit with num_stack_levels=0.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=0)`
Beginning AutoGluon training ... Time limit = 416s
AutoGluon will save models to "/content/AutogluonModels/ag-20260318_184643"
Train Data Rows:    135
Train Data Columns: 3
Label Column:       target
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9799.03 MB
	Train Data (Original)  Memory Usage: 0.00 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 3 | ['PC1', 'PC2', 'PC3']
	Types of features in processed data (raw dtype, special dtypes):
		('float', []) : 3 | ['PC1', 'PC2', 'PC3']
	0.1s = Fit runtime
	3 features in original data used to generate 3 features in processed data.
	Train Data (Processed) Memory Usage: 0.00 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.1s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 415.53s of the 415.50s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.16%)
	-0.5264	 = Validation score   (-mean_absolute_error)
	30.93s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 376.39s of the 376.37s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.15%)
	-0.5505	 = Validation score   (-mean_absolute_error)
	29.03s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 341.99s of the 341.97s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-0.6226	 = Validation score   (-mean_absolute_error)
	1.03s	 = Training   runtime
	0.25s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 340.67s of the 340.64s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=3.89%)
	-0.5686	 = Validation score   (-mean_absolute_error)
	27.61s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 307.74s of the 307.71s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-0.6231	 = Validation score   (-mean_absolute_error)
	0.95s	 = Training   runtime
	0.26s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 306.50s of the 306.47s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.542	 = Validation score   (-mean_absolute_error)
	63.67s	 = Training   runtime
	0.25s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 236.42s of the 236.40s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.04%)
	-0.5745	 = Validation score   (-mean_absolute_error)
	19.81s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 207.74s of the 207.71s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.561	 = Validation score   (-mean_absolute_error)
	68.09s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 131.30s of the 131.27s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.65%)
	-0.5811	 = Validation score   (-mean_absolute_error)
	30.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 95.00s of the 94.98s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=3.90%)
	-0.5752	 = Validation score   (-mean_absolute_error)
	25.11s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 61.09s of the 61.07s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (2 workers, per: cpus=1, gpus=0, memory=0.00%)
	-0.5383	 = Validation score   (-mean_absolute_error)
	68.84s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the -16.66s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/9.5 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.5, 'NeuralNetTorch_r79_BAG_L1': 0.318, 'NeuralNetFastAI_BAG_L1': 0.182}
	-0.5162	 = Validation score   (-mean_absolute_error)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 432.44s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 48.5 rows/s (17 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20260318_184643")

In [21]:
# View the Model Leaderboard
# This shows you which models (XGBoost, Neural Nets, etc.) performed best within the time frame
lb = predictor.leaderboard(test_data_ag, silent=True)
print("\n--- Model Leaderboard ---")
print(lb)

--- Model Leaderboard ---
                        model  score_test  score_val          eval_metric  \
0   NeuralNetTorch_r79_BAG_L1   -0.599807  -0.538332  mean_absolute_error
1           LightGBMXT_BAG_L1   -0.605981  -0.526384  mean_absolute_error
2             LightGBM_BAG_L1   -0.608627  -0.550472  mean_absolute_error
3         WeightedEnsemble_L2   -0.616942  -0.516241  mean_absolute_error
4      RandomForestMSE_BAG_L1   -0.632124  -0.622625  mean_absolute_error
5       NeuralNetTorch_BAG_L1   -0.656171  -0.560999  mean_absolute_error
6        CatBoost_r177_BAG_L1   -0.657903  -0.575160  mean_absolute_error
7        ExtraTreesMSE_BAG_L1   -0.661953  -0.623129  mean_absolute_error
8             CatBoost_BAG_L1   -0.669877  -0.568553  mean_absolute_error
9      NeuralNetFastAI_BAG_L1   -0.677070  -0.541974  mean_absolute_error
10       LightGBMLarge_BAG_L1   -0.680279  -0.581111  mean_absolute_error
11             XGBoost_BAG_L1   -0.769280  -0.574462  mean_absolute_error

    pred_time_test  pred_time_val    fit_time  pred_time_test_marginal  \
0         0.078495       0.072637   68.840869                 0.078495
1         1.176999       0.028970   30.932512                 1.176999
2         0.021521       0.011448   29.033598                 0.021521
3         2.217534       0.351490  163.564406                 0.003072
4         0.116243       0.247420    1.029086                 0.116243
5         0.060694       0.094443   68.088271                 0.060694
6         0.017838       0.014383   25.105375                 0.017838
7         0.101543       0.259980    0.952761                 0.101543
8         0.205422       0.016708   27.607962                 0.205422
9         0.958968       0.248704   63.666153                 0.958968
10        0.024420       0.012846   30.266386                 0.024420
11        0.082515       0.044138   19.812893                 0.082515

    pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  \
0                 0.072637          68.840869            1       True
1                 0.028970          30.932512            1       True
2                 0.011448          29.033598            1       True
3                 0.001179           0.124871            2       True
4                 0.247420           1.029086            1       True
5                 0.094443          68.088271            1       True
6                 0.014383          25.105375            1       True
7                 0.259980           0.952761            1       True
8                 0.016708          27.607962            1       True
9                 0.248704          63.666153            1       True
10                0.012846          30.266386            1       True
11                0.044138          19.812893            1       True

    fit_order
0          11
1           1
2           2
3          12
4           3
5           8
6          10
7           5
8           4
9           6
10          9
11          7

**Explantion of the results**

The autogluon has checked on 13 different models

In [22]:
# Generate Predictions for 2020-2024
# We drop the 'target' column from the test data to predict it
# # Ensures the model is forced to guess the result using only the input features (PC1, PC2) without "cheating" by looking at the answer.
preds = predictor.predict(test_data_ag.drop(columns=['target']))

In [23]:
# Back-transform by converting log values back to real BEV percentages
y_test_real = np.exp(test_data_ag['target'])
preds_real = np.exp(preds)

In [24]:
# Create unified results dataframe
all_results = pd.DataFrame({
    'Country': post_covid_fixed['Country'],
    'Year': post_covid_fixed['Year'],
    'Actual_BEV_%': y_test_real,
    'Predicted_BEV_%': preds_real
})

# Absolute error
all_results['Error_Abs'] = (all_results['Actual_BEV_%'] - all_results['Predicted_BEV_%']).abs()

# Loop year-wise
for year, year_df in all_results.groupby('Year'):

    print(f"====>YEAR: {int(year)} PREDICTION RESULTS")

    # Leaders
    print(f"\n**** LEADERS CLUSTER ({int(year)}) ****")
    leaders_df = (
        year_df[year_df['Country'].isin(leaders_list)]
        .sort_values('Actual_BEV_%', ascending=False)
    )
    print(leaders_df[['Country', 'Actual_BEV_%', 'Predicted_BEV_%', 'Error_Abs']]
          .to_string(index=False))

    # Followers
    print(f"\n**** FOLLOWERS CLUSTER ({int(year)}) ****")
    followers_df = (
        year_df[year_df['Country'].isin(followers_list)]
        .sort_values('Actual_BEV_%', ascending=False)
    )
    print(followers_df[['Country', 'Actual_BEV_%', 'Predicted_BEV_%', 'Error_Abs']]
          .to_string(index=False))

====>YEAR: 2025 PREDICTION RESULTS

**** LEADERS CLUSTER (2025) ****
       Country  Actual_BEV_%  Predicted_BEV_%  Error_Abs
       Denmark         69.53        15.670119  53.859881
   Netherlands         37.68        15.413776  22.266224
        Sweden         37.58        15.884517  21.695483
       Belgium         35.40        13.532464  21.867536
       Austria         22.34        12.642888   9.697112
        France         21.01        15.875614   5.134386
       Germany         20.08        16.163254   3.916746
         Spain         10.19        12.509192   2.319192
       Hungary          9.36        15.486421   6.126421
        Poland          7.73        10.282878   2.552878
         Italy          7.18        12.419387   5.239387
       Romania          6.59        12.868287   6.278287
Czech Republic          6.55        12.643937   6.093937

**** FOLLOWERS CLUSTER (2025) ****
   Country  Actual_BEV_%  Predicted_BEV_%  Error_Abs
   Finland         37.81        11.763427  26.046573
     Malta         33.88         9.162637  24.717363
Luxembourg         28.09         9.215140  18.874860
  Portugal         24.26        12.466840  11.793160
   Ireland         19.89         9.988208   9.901792
  Slovenia         11.60         9.302233   2.297767
    Cyprus         10.68         8.981985   1.698015
    Latvia          8.05         9.420610   1.370610
 Lithuania          7.99         9.604818   1.614818
   Estonia          7.74         9.351472   1.611472
    Greece          6.81        11.997451   5.187451
  Bulgaria          5.93         9.666339   3.736339
  Slovakia          5.56         9.748833   4.188833
   Croatia          2.64         7.396942   4.756942

In [25]:
# Filter the results as per the clusters
all_results['Cluster'] = all_results['Country'].apply(
    lambda x: 'Leaders' if x in leaders_list else 'Followers'
)

# Create the Leaders and Followers dataFrame and sort in alphabetical order for easier visualisation
leaders_results_df = (
    all_results[all_results['Cluster'] == 'Leaders']
    .sort_values(by=['Country', 'Year'])
)

followers_results_df = (
    all_results[all_results['Cluster'] == 'Followers']
    .sort_values(by=['Country', 'Year'])
)

# Save the data frame in an excel file
leaders_results_df.to_excel("Trial3_AutoGluon_Leaders_Results.xlsx", index=False)
followers_results_df.to_excel("Trial3_AutoGluon_Followers_Results.xlsx", index=False)